export const USER_ACTIONS = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    CLEAR_SESSION: 'CLEAR_SESSION',
    LOADED_DEPENDENTS: 'LOADED_DEPENDENTS',
    DEPENDENT_DELETED: 'DEPENDENT_DELETED',
    DEPENDENT_ADDED: 'DEPENDENT_ADDED',
    DEPENDENT_UPDATED: 'DEPENDENT_UPDATED',
    PROFILE_UPDATED: 'PROFILE_UPDATED' 
  };
  
  export const PATIENT_ACTIONS = {
    LOAD: 'LOAD_PATIENT'
  };
  
  export const ALLERGY_INTOLERANCE_ACTIONS = {
    LOADED: 'ALLERGY_INTOLERANCE_LOADED'
  };
  
  export const APPOINTMENT_ACTIONS = {
    LOADED: 'APPOINTMENT_LOADED'
  };
  
  export const APPOINTMENT_RESPONSE_ACTIONS = {
    LOADED: 'APPOINTMENT_RESPONSE_LOADED'
  };
  
  export const CONDITION_ACTIONS = {
    LOADED: 'CONDITION_LOADED'
  };
  
  export const ENCOUNTER_ACTIONS = {
    LOADED: 'ENCOUNTER_LOADED'
  };
  
  export const MEDICATION_REQUEST_ACTIONS = {
    LOADED: 'MEDICATION_REQUEST_LOADED'
  };
  
  export const OBSERVATION_ACTIONS = {
    LOADED: 'OBSERVATION_LOADED'
  };
  
  export const SCHEDULE_ACTIONS = {
    LOADED: 'SCHEDULE_LOADED'
  };
  
  export const SERVICE_REQUEST_ACTIONS = {
    LOADED: 'SERVICE_REQUEST_LOADED'
  };
  
  export const COMPOSITION_ACTIONS = {
    LOADED: 'COMPOSITION_ACTIONS'
  };
  
  export const SLOT_ACTIONS = {
    LOADED: 'SLOT_LOADED'
  };
  
  export const LOADING = {
    SET_LOADING: 'SET_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    LOADING_PROFILE: 'LOADING_PROFILE',
    LOADED_PROFILE: 'LOADED_PROFILE',
    LOADING_DEPENDANTS: 'LOADING_DEPENDANTS',
    LOADED_DEPENDANTS: 'LOADED_DEPENDANTS',
    LOADING_HEALTH_RECORDS: 'LOADING_HEALTH_RECORDS',
    LOADED_HEALTH_RECORDS: 'LOADED_HEALTH_RECORDS',
  };
  
  export const SET_ALERT = 'SET_ALERT' // set alert
  
  export const PROFILE_ACTIONS = {
    LOADED: 'PROFILE_LOADED',
    UPDATED: 'PROFILE_UPDATED'
  }
  
  export const HISTORY_ACTIONS = {
    LOADED_ALLERGIES: 'LOADED_ALLERGIES',
    LOADED_COMPOSITION: 'LOADED_COMPOSITION',
    LOADED_CONDITION: 'LOADED_CONDITION',
    LOADED_ENCOUNTER: 'LOADED_ENCOUNTER',
    LOADED_MEDICATION_REQUEST: 'LOADED_MEDICATION_REQUEST',
    LOADED_OBSERVATION: 'LOADED_OBSERVATION',
    LOADED_SERVICE_REQUEST: 'LOADED_SERVICE_REQUEST',
  };
  
  export const NETWORK_ACTIONS = {
    UPDATE: 'UPDATE_NETWORK_STATUS',
  }
  