export const USER_ACTIONS = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    CLEAR_SESSION: 'CLEAR_SESSION',
    LOADED_PATIENTS: 'LOADED_PATIENTS',
    PATIENT_DELETED: 'PATIENT_DELETED',
    PATIENT_ADDED: 'PATIENT_ADDED',
    PATIENT_UPDATED: 'PATIENT_UPDATED',
    PROFILE_UPDATED: 'PROFILE_UPDATED' 
  };
  
  export const PATIENT_ACTIONS = {
    LOAD: 'LOAD_PATIENT'
  };
    
  
  export const LOADING = {
    SET_LOADING: 'SET_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    LOADING_PROFILE: 'LOADING_PROFILE',
    LOADED_PROFILE: 'LOADED_PROFILE',
    LOADING_PATIENTS: 'LOADING_PATIENTS',
    LOADED_PATIENTS: 'LOADED_PATIENTS', 
  };
  
  export const SET_ALERT = 'SET_ALERT' // set alert
  
  export const PROFILE_ACTIONS = {
    LOADED: 'PROFILE_LOADED',
    UPDATED: 'PROFILE_UPDATED'
  }
   
  
  export const NETWORK_ACTIONS = {
    UPDATE: 'UPDATE_NETWORK_STATUS',
  }
  